/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package praktikum;

import javafx.application.Application;

import javafx.stage.Stage;

public class App extends Application {
    @Override
    public void start(Stage primaryStage) {


        Halaman1 halaman1 = new Halaman1(primaryStage);
        halaman1.showPanel();

        
    }
    public static void main(String[] args) {
        launch(args);
    }
}

